name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['v0.9.5', 'v0.10.0', 'nightly']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
    
    - name: Run tests
      run: make test
